### ISSUE TITLE
Coupling with Fenics/Firedrake

### ISSUE THREAD

**Issue by Jagirhussan** [reaktoro/reaktoro#106]
Hi,
   I would like to perform a reactive flow solve within a relatively complex 3D domain. Is there a way to couple reaktoro with packages like Fenics or Firedrake. I was unable to get the example demo-advection-diffusion-reaction-fenics.py at
https://bitbucket.org/reaktoro/reaktoro/src/fenics-demo/demos/python/demo-advection-diffusion-reaction-fenics.py going.

Any input would be very useful.
Thanks
Jagir

**Comment by allanleal** [comment]
Hi, the bitbucket repository is not up to date. This has been done in the past. The script you mention could be used as a base. Note also that FEniCS has changed a lot since the creation of that script. Can you contact me directly, please at allan.leal@erdw.ethz.ch? We could discuss more about how to proceed with this. Would you be willing to helping up fixing that fenics demo in Reaktoro?

**Comment by allanleal** [comment]
I'll close this as not much has happened in this regard (FEniCS+Reaktoro) lately. Feel free to contact me if there are interests in this development.
