### ISSUE TITLE
Investigate changing `cardano` for numerical `PolynomialSolver`

### ISSUE THREAD

**Issue by tadeu** [reaktoro/reaktoro#108]
Should also add the rest of `eigen3`, as commented in:

https://github.com/reaktoro/reaktoro/pull/94#discussion_r317892867

**Comment by allanleal** [comment]
Hi Tadeu, thanks for opening this issue. I'm not sure if this is needed anymore, so I'll close this now. An alternative is to replace `cardano` with Newton, which can be cheaper (if good initial guesses are given, which is possible), since `cardano` depends on multiple calls to expensive math functions (e.g. `cbrt`, `cos` , `acos` , `cbrt`). Another approach is to implement a new `cardanoRealRootsOnly` method that produces only real roots (so that `cos`, `acos`, `sqrt`, etc. are not executed just to get complex roots (which are not used anyway)) . I will check this out in the near future.
