### ISSUE TITLE
ChemicalSystem usage does not seem to be thread safe

### ISSUE THREAD

**Issue by rafaelaugustoalves** [reaktoro/reaktoro#123]
When using OpenMP, constructing the ChemicalSystem of each thread from a unique ChemicalEditor leads to error inside Eigen. The same happens when using the same ChemicalSystem for multiple threads.

```cpp
void test_parallel_reaktoro (
    int testing_option
) 
{
    using namespace Reaktoro;
    std::string p_chemical_species = "Na+ NaOH(aq) Cl- NaCl(aq) HCl(aq) H+ H2O(l) OH-";
    std::string p_mineral_species = "Halite";

    Database const test_database("supcrt98.xml");

    // 0: each ChemicalSystem created from a "different" ChemicalEditor. Works fine
    // 1: each ChemicalSystem created from the same ChemicalEditor. Problem in Eigen
    // Regarless of option, both work when not using 'omp parallel'
    std::vector<ChemicalSystem> all_chemical_systems;
    auto num_threads = omp_get_max_threads();
    switch (testing_option) {
        case 0: {
            for (auto i = 0; i < num_threads; ++i) {
                auto const temp_chemical_editor = create_chemical_editor(
                    p_chemical_species,
                    p_mineral_species,
                    test_database
                );
                auto const chemical_system = ChemicalSystem(temp_chemical_editor);
                all_chemical_systems.push_back(chemical_system);
            }
            break;
        }
        case 1: {
            auto const chemical_editor = create_chemical_editor(
                p_chemical_species,
                p_mineral_species,
                test_database
            );
            for (auto i = 0; i < num_threads; ++i) {
                auto const chemical_system = ChemicalSystem(chemical_editor);
                all_chemical_systems.push_back(chemical_system);
            }
            break;
        }
        default: {
            throw std::invalid_argument("Invalid option");
        }
    }
    
    auto num_runs = 50;
    #pragma omp parallel for
    for (auto i = 0; i < num_runs; ++i) {
        auto current_thread = omp_get_thread_num();
        auto const& p_chemical_system = all_chemical_systems[current_thread];

        EquilibriumProblem problem(p_chemical_system);
        problem.setTemperature(100, "celsius");
        problem.setPressure(20, "bar");
        problem.add("H2O(l)", 5, "mol");
        problem.add("NaCl(aq)", 1, "mol");
    
        ChemicalState p_chemical_state = equilibrate(problem);

        std::ostringstream phrase_stream;
        phrase_stream << "\n Solved case: " << i << " using thread: " << current_thread;
        std::cout << phrase_stream.str();
    }
}


Reaktoro::ChemicalEditor create_chemical_editor(
    std::string p_aqueous_species,
    std::string p_mineral_species,
    Reaktoro::Database const& p_database
)
{
    using namespace Reaktoro;
    ChemicalEditor editor(p_database);
    editor.addAqueousPhase(p_aqueous_species);
    editor.addMineralPhase(p_mineral_species);
    return editor;
}
```

**Comment by allanleal** [comment]
Thanks Rafael. 

The class `ChemicalSystem`, although immutable from the point of view that there is no `set` methods (once constructed, it cannot be modified, e.g., add more phases), it has some function objects inside that use [memoization optimization](https://en.wikipedia.org/wiki/Memoization) to avoid recomputation of properties, say, for the same temperature and pressure (e.g., water equation of state). 

If we removed these optimizations, the class would be thread-safe. However, this could lead to drop in performance. So, my understanding is that we should keep these optimizations (for now), and create (as @tadeu pointed out) an object of `ChemicalSystem` for each thread, which is what you do above.

However, I don't really like this, and I think we should in the future have `ChemicalSystem` truly immutable and thread-safe, so that we can indeed only require one object for it. 

In the meanwhile, if you have ideas on how to improve the creation of these `ChemicalSystem` objects, for each thread, in a more straightforward way, it would be a nice contribution! :)

**Comment by allanleal** [comment]
Hi Rafael, there is now a new version of Reaktoro, v2 (please consult the website https://reaktoro.org). This new version still relies heavily on memorization techniques to avoid expensive calculations when the same arguments of an expensive function are provided again. Therefore, to use Reaktoro in different parallel processes/threads, it is still necessary that objects of class `Database`, `ChemicalSystem`, etc. be cloned for each thread/process to avoid race conditions. I'll try to add a tutorial in the near future demonstrating how this can be accomplished.
