### ISSUE TITLE
Installation problem in Google Colab

### ISSUE THREAD

**Issue by yohanesnuwara** [reaktoro/reaktoro#134]
I tried to clone the repo in my Colab:
`! git clone https://github.com/reaktoro/reaktoro.git`
And then import the system and append
`import os,sys`
`sys.path.append('/content/reaktoro')`
And then I try the following code:
`from reaktoro import *`
`editor = ChemicalEditor()`
It turns an error:
`ChemicalEditor not defined`

I also try to install it otherwise:
`!pip install git+https://github.com/reaktoro/reaktoro`
But it also turns an error:
`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I'm wondering to use reaktoro in Google Colab. I'd be glad to hear your reply from you very soon.

**Comment by allanleal** [comment]
Hi @yohanesnuwara , I don't have experience using Colab. The easiest way to get reaktoro working is using conda. I would be surprised if Colab does not support conda environments. Installing reaktoro via pip is not possible at the moment ( @volpatto ). You should do `conda install conda-forge::reaktoro` instead.

**Comment by volpatto** [comment]
We have an Issue for putting Reaktoro in `pip`. However, since Reaktoro's core is written as C++, packing Reaktoro's python bindings is not straightforward at this moment. We need some time to figure it out how we could put Reaktoro there.

Meanwhile, I would recommend use Reaktoro from `conda` (as @allanleal said above). The easier way, in my understanding, would be:

1. Download `miniconda` inside a Colab's notebook. Something like:
```console
!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
```
2. Install `miniconda`:
```console
!bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
```
3. Then, install Reaktoro as suggested by Allan:
```console
!conda install conda-forge::reaktoro
```
4. Add conda package's path to Colab Python's path (please replace `X` by your Python's version there):
```python
import sys
sys.path.append('/usr/local/lib/python3.X/site-packages')
```

The above steps (hopefully) would do the job for now. Note that you can install any (working) conda package this way.

**Comment by yohanesnuwara** [comment]
Thanks @allanleal and @volpatto. I'm a beginner in miniconda, I've tried this so far, and then directly `from reaktoro import *`, but then reaktoro still can't be recognized. I'm wondering if I skipped any step. Here, I attach a ZIP file that contains my ipynb file. 

[reaktoro.zip](https://github.com/reaktoro/reaktoro/files/4096830/reaktoro.zip)

**Comment by allanleal** [comment]
Hi @yohanesnuwara . Instead of:

~~~
sys.path.append('/usr/local/lib/python3/site-packages')
~~~

try this:

~~~
sys.path.append('/usr/local/lib/python3.6/site-packages')
~~~

`reaktoro` module is not found because the path to where it was installed on Colab is probably not set correctly. 

Let me know!

**Comment by allanleal** [comment]
By the way, you can chat with us on our [**Gitter Channel**](https://gitter.im/reaktoro/community) for a faster response.

**Comment by volpatto** [comment]
> Thanks @allanleal and @volpatto. I'm a beginner in miniconda, I've tried this so far, and then directly `from reaktoro import *`, but then reaktoro still can't be recognized. I'm wondering if I skipped any step. Here, I attach a ZIP file that contains my ipynb file if you would like to check my code.
> 
> [reaktoro.zip](https://github.com/reaktoro/reaktoro/files/4096830/reaktoro.zip)

No worries, we can help you. I'll have look later today. I will try to provide to you a working example of importing `reaktoro` in a Colab notebook.

**Comment by volpatto** [comment]
@yohanesnuwara and @allanleal, sorry, I did some mistakes in my previous answer. I figured out how one can use `reaktoro` inside a Colab notebook. Please check it out [here](https://colab.research.google.com/drive/1TTud1YcbeL1g0tIxyur9qviL5HWiRmyg).

Please let me know if it worked properly (or not).

**Comment by allanleal** [comment]
Hi @yohanesnuwara , [these instructions](https://reaktoro.org/installation/installation-in-google-colab.html) on using Google Colab should help you. This has been tested with the new version 2 of Reaktoro.
