### ISSUE TITLE
Tests have errors and fails in a Manjaro fresh installation

### ISSUE THREAD

**Issue by volpatto** [reaktoro/reaktoro#135]
Hi all,

I think that maybe something is not properly set in my installation. I precisely followed the [steps from here](https://reaktoro.org/installation.html), with conda devenv, and building `reaktoro` inside its env. Compilation seems fine for a first build with `cmake -P install` as well for `inv compile`.

When I run `pytest -n auto .`, I get 6 errors and 22 failing tests. Below I provide my output gathered from my Terminal.

[pytest_result.txt](https://github.com/reaktoro/reaktoro/files/4137013/pytest_result.txt)

My OS is a Manjaro 18.1.5, my Linux Kernel is 5.4.14.

Anyone knows what is the reason behind these errors and fails? I see that the errors are related to `ThermoFun`, while fails are related to regressions' diffs.

**Comment by volpatto** [comment]
Here is my `conda list` output:

[conda_list_output.txt](https://github.com/reaktoro/reaktoro/files/4137014/conda_list_output.txt)

I also tried to replicate the steps inside `travis.yml`. But results are the same.

**Comment by volpatto** [comment]
It properly works on Ubuntu 18.04. I noticed that builds behave different in each platform. Still I don't know why.

**Comment by allanleal** [comment]
@gdmiron This is for you! :)

@volpatto We are already of this. It's still not clear what is going on with the most recent build of ThermoFun in conda-forge.

**Comment by allanleal** [comment]
If you pin `thermofun` in your `environment.devenv.yml` to a previous version (instead of letting it get the most recent one, then this works apparently).

We need to either start pinning versions for dependencies, or have nightly CI runs that will check what is the current status of building/running reaktoro with the current dependencies in conda package.

**Comment by volpatto** [comment]
Great, @allanleal! I think that it's nice to have a stable release and `nightly` releases. Stable should pin versions for dependencies, in order to guarantee, well, stability and robustness of installation. Even with `conda`, we can sometime face platform related problems. To avoid such problems, I think that pinning can help.

**Comment by volpatto** [comment]
> If you pin `thermofun` in your `environment.devenv.yml` to a previous version (instead of letting it get the most recent one, then this works apparently).
> 
> We need to either start pinning versions for dependencies, or have nightly CI runs that will check what is the current status of building/testing reaktoro with the current dependencies in conda package at their latest version.

Good to know, I will give it a try

**Comment by gdmiron** [comment]
You can also downgrade  `conda install thermofun=0.2.2` or when creating the environment do `conda create -n rkt reaktoro thermofun=0.2.2`

This is all new and strange for me :). If I recompile and install reaktoro in an env that has thermofun 0.3.0, the demo works OK. I think the issue is related to the fact that the reaktoro release from conda  was compiled with thermofun 0.2.2. There is no actual change in thermofun 0.3.3 that would make the test fail.

**Comment by allanleal** [comment]
Hopefully this issue should not exist anymore, for both Reaktoro v1 and v2. In case this persists, please reopen. Thanks for reporting.
