### ISSUE TITLE
Investigate why Phreeqc destructor is throwing an exception

### ISSUE THREAD

**Issue by OtavioPellicano** [reaktoro/reaktoro#161]
I made a test to run PHREEQC  input script by file:
```
    std::string database_path = "W:/reaktoro_processing/DATABASE/phreeqc.dat";
    std::string input_path = "W:/reaktoro_processing/IN/IW.pqi";
    std::string output_path = "W:/reaktoro_processing/OUT/IW.pqo";
    
    Phreeqc phreeqc(database_path);
    phreeqc.execute(input_path, output_path);
```
After I ran it, the Phreeqc destructor threw an exception caused by a raw pointer (see the image below)

![image](https://user-images.githubusercontent.com/27929707/95334225-369e9580-0884-11eb-8790-c0e32cffa0ef.png)

**Comment by tadeu** [comment]
I think that the problem is because the `ostream` is being deleted here: https://github.com/reaktoro/reaktoro/blob/d8bbb227b31e7a68004151ce118651134fbc68db/Reaktoro/Interfaces/PhreeqcUtils.cpp#L66

```cpp
auto execute(PHREEQC& phreeqc, std::string input, std::string output) -> void
{
...
    // Delete the dynamically allocated stream objects
    if(out != nullptr) delete out;  // <--
```

leaving a dangling pointer inside `PHRQ_io`, and `Phreeqc` will try to delete an already deleted pointer here:

https://github.com/reaktoro/reaktoro/blob/5b9db47b1c1200c2fb46d886e42442724bc1e6de/thirdparty/phreeqc/Phreeqc.cpp#L46

```cpp
Phreeqc::~Phreeqc(void)
{

	clean_up();
	
	PHRQ_free_all();
	if (phrq_io == &ioInstance)
	{
		this->phrq_io->clear_istream();
		this->phrq_io->close_ostreams();  // <--
	}
}
```

**Comment by tadeu** [comment]
Perhaps the API should be changed so that `PHRQ_io` doesn't change the ownership of the streams, i.e., it shall not try to delete them if it wasn't `PHRQ_io` that allocated them?

But that also doesn't solve the dangling pointer problem if the stream is deleted externally. If we don't want to deal with transference of ownership, perhaps it could work with `std::shared_ptr<std::stream>`, but this would break the API.

**Comment by allanleal** [comment]
Hi guys, thanks for reporting this.

I think using `std::shared_ptr` as suggested by Tadeu should solve this:

Instead of:
~~~c++
std::ofstream* out = output.empty() ? nullptr : new std::ofstream(output);
~~~

we do:

~~~c++
std::shared_ptr<std::ofstream> out = output.empty() ? nullptr : std::make_shared<std::ofstream>(output);
~~~

I haven't tested this fix yet. This piece of initialization code was very much inspired by what PHREEQC does internally - at the time I ported it to Reaktoro, `std::shared_ptr` (or perhaps `std::unique_ptr`) should have been used.

@OtavioPellicano would you kindly prepare a PR for this?

**Comment by OtavioPellicano** [comment]
Sure!
