### ISSUE TITLE
Possible to solve arbitrary equilibrium?

### ISSUE THREAD

**Issue by jlmaccal** [reaktoro/reaktoro#181]
Is it possible to reaktoro to solve arbitrary chemical equilibrium problems that are not based on an existing database?

I am interested in solving biomolecular equilibrium problems that involve a single phase and might have a set of reactions like:
```
50 L   <=> M
P + L  <=> PL
P + M  <=> PM
PM + L <=> PML
```

I can specify the equilibrium constants for each reaction, which can be converted into apparent standard chemical potentials. I would want to model this as an ideal system with unity activity coefficient.

Is there a way to construct and solve such a system with reaktoro? I have had little success solving this other approaches due to the large stochimetric coefficient on `L`.

**Comment by allanleal** [comment]
You can bypass the database entirely. You could construct the `Element`, `Species`, and `Phase` objects necessary for your application. 

Assuming python below (but the same can be done in C++). 

~~~py
# Creating the Element objects before creating the Species objects
elementL = Element()
elementL.setName("L")
elementL.setMolarMass(1.234)  # kg/mol (optional - if you have it)

elementM = Element()
elementM.setName("M")
elementM.setMolarMass(2.345)  # kg/mol (optional - if you have it)

elementP = Element()
elementP.setName("P")
elementP.setMolarMass(3.456)  # kg/mol (optional - if you have it)

# Creating the Species objects before creating the Phase objects (one or more phases)
speciesL = Species()
speciesL.setName("L")
speciesL.setFormula("L")
speciesL.setElements({elementL: 1})  # species L is composed on a single element L (e.g., Fe(s) is composed of element Fe)

speciesM = Species()
speciesM.setName("M")
speciesM.setFormula("M")
speciesM.setElements({elementM: 1})  # species M is composed of M:1

speciesPM = Species()
speciesPM.setName("PM")
speciesPM.setFormula("PM")
speciesPM.setElements({elementP: 1, elementM: 1})  # species PM is composed of P:1 and M:1

species = [speciesL, speciesM, speciesPM]  # the list of the constructed species

# Creating the Phase object
phase = Phase()
phase.setName("MyPhaseName")
phase.setType(PhaseType.Liquid)  # use any of Solid, Liquid, Gas, Plasma
phase.setSpecies(species)  # L, M, PM in this list

# This is the step where we "teach" the Phase object how to compute the 
# standard thermodynamic properties of the species at any given T and P

def my_phase_thermo_model_fn(res, T,  P):
    G0 = res.standard_partial_molar_gibbs_energies  # let's use G0 as a shorthand notation for the array of G0 values of the species
    G0[0] = 1.2 + 1.234 * T  # this is G0 of species L
    G0[1] = 2.3 + 1.435 * T  # this is G0 of species M
    G0[2] = 5.6 + 2.556 * T  # this is G0 of species PM

phase.setThermoModel(my_phase_thermo_model_fn)

# Now we "teach" the Phase object how to compute the 
# activities of the species at any given T, P, composition
# For this, it is easier to rely on existing models.

mixture = LiquidMixture(species)
phase.setChemicalModel(liquidChemicalModelIdeal(mixture))

# We can now construct our ChemicalSystem object and proceed with equilibrium calculations
system = ChemicalSystem([phase])
~~~

This is not a full tutorial. I'll be happy though to guide you through the process. If interested, we can continue this communication via [Gitter](https://gitter.im/allanleal)

FYI, I'm working on v2.0 of Reaktoro, and setting up this problem there would be simpler since it supports logK models out-of-the-box and you don't need to do the conversion yourself. The API is also simpler. However, I haven't produced a conda package for it yet (in case you are using conda). You would need to compile Reaktoro v2.0-preview (which is simple, but not every user is used to do this).

**Comment by allanleal** [comment]
I'll close this issue now, but we can further interact here if needed.

**Comment by jlmaccal** [comment]
Thanks for your help. I’m still having a few issues. I sent a message on gutter. We can continue the conversation there.
