### ISSUE TITLE
Tutorial Problem... Solubility of carbon dioxide in water

### ISSUE THREAD

**Issue by wietmazairac** [reaktoro/reaktoro#199]
I have a problem with the tutorial named **_Solubility of carbon dioxide in water_** on the next page...
[https://mybinder.org/v2/gh/reaktoro/reaktoro-jupyter/master?filepath=tutorial%2Foverview.ipynb](https://mybinder.org/v2/gh/reaktoro/reaktoro-jupyter/master?filepath=tutorial%2Foverview.ipynb)

The tutorial states that a decrease in pressure will reduce the amount of CO2.
However, the picture shows the opposite.
What's going on?

![image](https://user-images.githubusercontent.com/40294132/114025913-f42b3500-9875-11eb-88c8-4f69d0ece6c1.png)

**Comment by volpatto** [comment]
Hi, @wietmazairac.

Thank you for pointing that. Good catch!

I think you are right. If you increase the pressure, CO2(g) is expected to increase its "dissolved" amount in the aqueous phase. Sorry for the confusion.

Sorry to ask you, but could you please open the same issue at [reaktoro-jupyter repository](https://github.com/reaktoro/reaktoro-jupyter)?

Cheers!

**Comment by allanleal** [comment]
> If you increase the pressure, CO2(g) is expected to increase its "dissolved" amount in the aqueous phase. Sorry for the confusion.

This is what is going on in that figure. I did not check the tutorial (on vacation ATM), but that figure shows that the amount of CO2(g) (CO2 is gaseous form) is decreasing with an increase in pressure because it is getting more dissolved in the aqueous solution. 

The tutorial perhaps shows the concentration of carbon element in the aqueous solution (which should increase with increase in pressure). 

So, the figure above looks correct. 

The text on the bottom, however, should be more aligned with what the figure presents. I'll ping @mtsveta here who is taking care of the Jupyter Notebooks.

**Comment by wietmazairac** [comment]
Thanks for the help. I appreciate it.

**Comment by volpatto** [comment]
> So, the figure above looks correct.

Yeah, sorry, @allanleal. I agree with you, and I got confused by the text too. My goal was to state that the (plotted) result is correct.

> Thanks for the help. I appreciate it.

@wietmazairac thank you for the issue https://github.com/reaktoro/reaktoro-jupyter/issues/18. I will close this issue here for now, since it will be properly addressed in `reaktoro-jupyter` repo, which is the repo where the notebooks are hosted.

**Comment by allanleal** [comment]
> Yeah, sorry, @allanleal. I agree with you, and I got confused by the text too. My goal was to state that the (plotted) result is correct.

Yes, that needs improvements! Thanks, Diego, for taking care of this!

**Comment by allanleal** [comment]
> Yeah, sorry, @allanleal. I agree with you, and I got confused by the text too. My goal was to state that the (plotted) result is correct.

Yes, that needs improvements! Thanks, Diego, for taking care of this!
