### ISSUE TITLE
Pip Package Version Mismatch

### ISSUE THREAD

**Issue by MosGeo** [reaktoro/reaktoro#200]
I am noting a version mismatch between the conda and pip packages (1.2.3 VS 1.2.2) is the pip package not maintained and not recommended?

**Comment by volpatto** [comment]
@MosGeo thank you for reporting this issue. Indeed, the versions are mismatching, but this issue was due to a problem in our packaging procedure. In fact, the conda and pip packages are the same code. We will fix it as soon as we find some time (@allanleal is on holidays right now).

By the way, you successfully installed `reaktoro` using `pip`?

This pip version is the first Reaktoro's release in PyPI, so it is still experimental. I would recommend to use `conda` instead.

**Comment by allanleal** [comment]
Reaktoro is not officially available via `pip` at the moment, but this may become available in the near future. Right now focus is on further developing critical features in [Reaktoro v2](https://reaktoro.org) (the new version of Reaktoro), which can be installed via conda (please check these instructions: [Installation using Conda](https://reaktoro.org/installation/installation-using-conda.html)).
