### ISSUE TITLE
Run Reaktoro in Visual studio 2019

### ISSUE THREAD

**Issue by xzhao2** [reaktoro/reaktoro#206]
Hi Reaktoro folks,

I am writing this to ask if I can compile it in visual studio 2019? I installed it as instructed using anaconda and it worked very will. However I cannot see how Reaktoro perform the calculations in detail.

Thanks
Xinrui

**Comment by allanleal** [comment]
Hi Xinrui,

Did you try installing Reaktoro from conda using `conda install conda-forge::reaktoro`?

You'll actually want to do `conda install conda-forge::reaktoro=1.2.3` since the last version is `2.0.0.rc2`, for the new version of Reaktoro, but we are in the process of updating the website with new docs.

If you need to build Reaktoro yourself, then you should know how programming in Windows works, how to link libraries, etc.

You'll also need to set PYTHONPATH yourself to wherever you installed Reaktoro's Python package.

Please tell us more about what you've tried, the steps you took to compile, where you installed, and then we should be able to give you instructions on how to proceed.

**Comment by xzhao2** [comment]
Thanks for you quick reply, Allan. 

I have tried the installation from conda following the instructions and it works. Actually, I am trying to see how Reaktoro works (or more specifically, what the framework is like) and hope that inspires me. By using conda, where Reaktoro has been used as an interface, I could not see details. I am not familiar with any IDEs but Visual Studio. So I am thinking about if I can drag some .cpp and .hpp files into the source file of a project in Visual studio based on the makefile and compile it this way. Or do you know any other ways that allow me to advance the execution one statement at a time (like Debug > Step Into).

Your assistance is greatly appreciated.

**Comment by allanleal** [comment]
Hi Xinrui.

Do you mean dragging .hpp and .cpp files of Reaktoro, and compiling them in Visual Studio? This is not how you should do it. You'll need to use CMake to generate the Visual Studio project/solution for you.

In a terminal:
~~~
mkdir build
cd build
cmake .. 
~~~

but before this, you need to install the dependencies of Reaktoro, which are fetched from conda.

~~~
cd root/dir/of/reaktoro
conda devenv
~~~

this will create a conda environment called `reaktoro` with all the dependencies installed. You'll need to install conda-devenv as detailed on the website (`pip install conda-devenv` or `conda install conda-devenv`).

If you are beginning C++ programming/development, I recommend you to learn more about the tools (e.g., Visual Studio), how to link libraries, etc. 

I develop in Linux (using Visual Studio Code). If you can, give Linux (I use KDE Neon) a try, as it is much simpler (IMO). 

I'll close this issue. We can discuss more in this channel: https://gitter.im/reaktoro/community
