### ISSUE TITLE
Master and latest release fails to build with cmake

### ISSUE THREAD

**Issue by lmartinez-mirror** [reaktoro/reaktoro#207]
Hi, I've been working on packaging this project for Arch Linux through the AUR, however I cannot get this project to compile using either a tagged release or the master branch.

I've attached a build log below, but long story short, a source file might be missing the `<limits>` header.

[Build log for master branch](https://github.com/reaktoro/reaktoro/files/6835623/reaktoro-1.2.3.r10.gb680b40e-1-x86_64-build.log)

[Build log for latest release tarball](https://github.com/reaktoro/reaktoro/files/6835626/reaktoro-1.2.3-1-x86_64-build.log)

**Comment by allanleal** [comment]
Hi Luis,

I've been working on releasing Reaktoro v2.0 (see branch `v2.0.0rc` and daily progress on my fork https://github.com/allanleal/reaktoro/tree/v2.0.0rc).

It would make sense to create Arch releases for this version instead. Since a lot has changed in v2.0 on how Reaktoro is built (compared to v1+), you may want to avoid doing this twice. 

We can discuss more about this here https://gitter.im/reaktoro/community

**Comment by allanleal** [comment]
Hi @lmartinez-mirror . I'll close this issue, but feel free to reopen if the problem persists. Installation of Reaktoro v2 using CMake can be found in this new website: https://reaktoro.org/installation/installation-using-cmake.html
