### ISSUE TITLE
Flaky behavior while using to solve kinetic problems

### ISSUE THREAD

**Issue by alexandrebbruno** [reaktoro/reaktoro#23]
Hi guys,

I've just found some interesting behavior while I was using reaktoro to solve some kinetic problems that I think it worth to be mention here to open a discussion about it.

Some of the kinetic tests are given different results depending the number of processors used by the PC. 

Here are some of the results that I've obtained:
* result from test_path_solve_final_state_2 using pytest -n0 
https://sftp.esss.com.br/~abarbosa/finalStaten0.txt

* result from test_path_solve_final_state_2 using pytest -n8 
https://sftp.esss.com.br/~abarbosa/finalStaten8.txt

* numerical difference
https://sftp.esss.com.br/~abarbosa/diff.txt

Primary investigation pointed out that it could be something related to the VCode library, which is used during the integration process at line 214 in ODE.cpp, but I'm not quite sure about it 🤔 

What do you guys think about it? Are there anyone who have face anything like that? What you think about the idea of replace VCode by another one? 🤔 

more information about the test can be found at https://github.com/alexandrebbruno/Reaktoro/tree/study-kinetic-flaky.

**Comment by allanleal** [comment]
In general, one needs to create an instance of solver class (`EquilibriumSolver`, `KineticSolver`, `ODESolver`) for every thread to avoid racing conditions, since there are mutable state in these classes for efficiency reasons. I'm not sure if this is applicable to your use case, but this is a possible explanation. 

The `ODESolver` class (a wrapper to the cvode solver in C code) has copy constructor deleted because of the lack of support in copying state of the cvode context pointer. 

Please check if there is a solver object for each thread.

**Comment by tadeu** [comment]
@alexandrebbruno, the difference from serial to parallel there is just the number of processes used by [`pytest-xdist`](https://docs.pytest.org/en/3.0.0/xdist.html)?

`xdist` uses different processes instead of threads, so it would be harder to have race conditions (each process runs a different test, and each test will create different instances of the solve classes). Still, some other possible explanations would be:

* The tests are using a common system resource, e.g., one is reading a file while the other is modifying it
* The problem is not with parallelism but with the order the tests are run: state is "leaking" from one test to another (via global variable or fixture at module/session level). In this case, since `xdist` will change the tests order, it will expose this problem. To check for this you can try to run tests in random order with a single process, without passing `-n` flag, but using a plugin such as `pytest-randomly` or `pytest-random-order`.

**Comment by alexandrebbruno** [comment]
@tadeu.
Yes, the only diference between serial and parallel it is on the number of processes used to run those tests.
Thanks for the ideias, I'll check than as soon as I finish the report.
