### ISSUE TITLE
Chemical systems with the same properties delivering different results

### ISSUE THREAD

**Issue by hfcpeixoto** [reaktoro/reaktoro#258]
I have ran into a somewhat weird behaviour of Reaktoro due to two apparently identical problems delivering different results.

I have defined two instances of `ChemicalEditor`s with the exact same species. The only difference is the **order** of the gaseous species, which I are reversed in one of the editors. I use `"H2O(g) CO2(g)"` for the first, and `"CO2(g) H2O(g)"` for the second.
The entire setup is done rigorously in the same manner for both problems. It turns out that after equilibrating the chemical states, results slightly differ (absolute error < 1e-11). 

This doesn't seems as much, but in an iterative setup, where systems are solved relying on the chemical state from the previous solution, it may lead to full blown divergence in just a few steps. And actually this was the issue that brought me here.

I have made [this MWE](https://colab.research.google.com/drive/1a8UkhXO6VvAPG_ahxrqbFTpHjNW5zOKM?usp=sharing) in Reaktoro v1 implementing the description above. I also make an attempt to reduce the absolute errors by using the Exact Hessian evaluation, which indeed bring the errors down, though not to plain zero, which I think would be the actual expected behaviour.

My guess is that by merely changing the input order of species affects the matrix row indices, which in turn leads to slightly different floating point solutions. 

**If** this turns out to be an actual problem to other users, I propose that `ChemicalEditor`s always store species in a well-defined order (alphabetically, probably), so as to make the `ChemicalSystem`s independent of input order.

P.S.: I have worked on the same issue in [this other MWE notebook](https://colab.research.google.com/drive/16ZWVmpo3bBg5ut4Iy4fNV7q9AXdp4Gzy?usp=sharing) using Reaktoro v2, and verified that the issue also happens, and actually with stronger differences. I am not as profficient in v2 as in v1, so I was not able to work the same Exact Hessian study as for v1.

**Comment by allanleal** [comment]
Hi Hélvio, thanks for reporting and also for taking the time to produce these organized Jupyter Notebooks showing the issue you are facing. I'll investigate this carefully and get back to you.

**Comment by allanleal** [comment]
Hi Hélvio, just noticed error in the notebook for Reaktoro v2:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/5825588/185115857-b0e52b44-5427-4a61-bfe7-c06e34257534.png">

Changing `state = ChemicalState(system1)` to `state = ChemicalState(system)` solves the issue in Reaktoro v2: the differences are insignificant (zero or below machine precision):

<img width="725" alt="image" src="https://user-images.githubusercontent.com/5825588/185116077-ea3992f0-2c53-4049-92b3-4f9a13d55637.png">

**Comment by allanleal** [comment]
For Reaktoro v1 (whose chemical equilibrium algorithm is inferior and less capable than the one in v2), you'll need to introduce a little bit of O2 (or H2) in the problem/state to get a better algorithm behavior:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/5825588/185118639-e656d96d-4817-4ecb-9141-4537cd9c5a49.png">

After introducing this bit of O2 in the problem (you can try smaller values, but below ~1e-15), this is the table of differences:

![image](https://user-images.githubusercontent.com/5825588/185119422-e65cb9b6-436d-4f2d-ad94-70a6854d29ee.png)

**So, differences are now around machine precision or below it. **

**Comment by allanleal** [comment]
I'm sure round-off errors are to blame. They happen even in calculations you'd not expect. Take for example the computations below, which we should expect identical results in infinitely precise numbers due to the commutativity property of multiplication:

~~~python
>>> print(f"{2.3 * (3.8 * 7.2):.32f}")
62.92799999999999727151589468121529
>>> print(f"{(2.3 * 3.8) * 7.2:.32f}")
62.92799999999999016608853708021343
~~~

These round-off errors (e.g., produced during matrix-vector multiplications, LU decomposition, etc.) can accumulate and affect the behavior of the algorithm (especially when there are species with amounts differing by many orders of magnitude). 

In the chemical equilibrium algorithm of Reaktoro v2, special care was taken to avoid round-off errors as much as possible and in some cases even eliminate them. 

Unfortunately, it is not possible (or not practical) to bring the strategies used in Reaktoro v2 to v1. 

For Reaktoro v1, improve algorithm behavior by ensuring that at least a tiny amount of O2 or H2 is present in the system.

**Comment by hfcpeixoto** [comment]
Hi Allan, thanks for the swift and thorough responses.

I am really sorry for that bug in the v2 notebook. I have fixed it and verified the same behaviour as you mentioned. Indeed v2 seems to have managed to deal with this apparent issue of species ordering.

I totally understand that improving v1 is not practical, when v2 is already on its way. As I am grasping, species ordering does not seem to be a problem in v2, and thus the suggestion to guarantee a unique order of species in chemical systems is not a priority, is this correct?

Regarding the v1 notebook, I was affraid that round-off errors were the actual problem, as they indeed seem to be. Thanks for the tip of using the tiny amounts for `O2` or `H2`. Could you ellaborate on why these specific species are to be used?

**Comment by allanleal** [comment]
Hi Hélvio, 

> As I am grasping, species ordering does not seem to be a problem in v2, and thus the suggestion to guarantee a unique order of species in chemical systems is not a priority, is this correct?

In Reaktoro's v2 chemical equilibrium algorithm, the order of the species does not matter because their corresponding variables (species amounts) are rearranged in each iteration (if needed) to minimize round-off errors. So, from the algorithm perspective, the order of the species is irrelevant. 

> Could you ellaborate on why these specific species are to be used?

When O2 or H2 are present, something happens both chemically and mathematically. 

From a chemical point of view, these species trigger *redox reactions* (by the way, Reaktoro does not need any special treatment to deal with these reactions, which happen naturally in the process of minimizing Gibbs energy; no need to specify anywhere that redox reactions (or any other reaction, unless kinetically controlled) should take place). 

From a mathematical point of view, this is more difficult to elaborate here (and I'll be short with the explanation for now). The mass balance equations are originally written in terms of element/charge conservation. These can be transformed into an equivalent system of linear equations in which the conservation is done in terms of what the literature calls *primary/basic species*. When this is done, it's easy to see the trouble: there is a mass balance equation for O2 and the right hand side should be sharp zero if no O2/H2 is added in the system. Because of round-off errors, a tiny amount may appear instead. Depending on its sign (positive or negative), the calculation may have a solution or not (or affect the overall computation). By adding O2 or H2 with some reasonable amount, you prevent this from happening. In Reaktoro v2, special care exists to resolve this (purely from linear algebra).

Apologies for not showing a more elaborate answer here, but this would take more time and preparation. Hope this helps for now.

**Comment by allanleal** [comment]
Hi Diego,

> In this sense (for Reaktoro v1), what about if we consider O2(g) in the gas phase setup (initialized with default value)?

Adding a tiny amount of O2(g) should also work, but then this gas needs to be added in the gaseous phase definition, which is not in that notebook.

**Comment by hfcpeixoto** [comment]
Thanks for the answers, @allanleal. Bearing these discussion in mind is more than enough to properly handle this issue while using v1, at least for my use case.
