### ISSUE TITLE
Uninstall script for Reaktoro

### ISSUE THREAD

**Issue by jdelorty** [reaktoro/reaktoro#27]
For people wanting to use a scientific software **uninstall** is the first solution to a failed installation on their system.
However as Reaktoro is not packaged and install/uninstall is not as straightforward as simply typing:
-  `apt install ...` and `apt remove ...` ,
- `brew install ...` and `brew uninstall ...`, 
- etc.

Should an uninstall script come with the whole directory, that would be helpful.
The current workaround proposed is by using the *install_manifest.txt* file coupled to a bash script called *uninstall.sh*:
```bash
#! /usr/bin/env/

for f in $(cat install_manifest.txt):
do
    rm -r $f
done
```
and then, in `reaktoro/build/` folder :
```
chmod 754 uninstall.sh
./uninstall.sh
```
and finally by running, in the folder where reaktoro has been cloned : 
```
sudo rm -r reaktoro/
```
I do not know however, if this is a viable solution.
***UPDATE*** -> This doesn't seem to uninstall any python binaries or libraries.
Thans for your attention !

**Comment by allanleal** [comment]
I've been thinking on this for a while since you brought this up. Here are the current difficulties:

1. A general approach that works for Linux, Windows, and macOS
2. The install target for the python package `reaktoro` uses `setuptools` and the `install_manifest.txt` then does not contain any info of the python-related files that are installed.

To solve 2, @tadeu , maybe it would make sense to use `setuptools` during build time (as we already do), and the install target is then based on copying the directory created by `setuptools` to the right path that `PYTHONPATH` knows about by default (e.g., `/usr/local/lib/pythonX.Y/site-packages` or `/home/user/miniconda3/envs/reaktoro/lib/pythonX.Y/site-packages`). Note: These paths are actually obtained automatically, and not manually provided. If this, `install_manifest.txt` will know about all files that got installed (headers, libs, and python modules/package).

If (2) is implemented, then (1) should become simpler, as we just have to delete the files listed in `install_manifest.txt` in a multi-platform way.

**Comment by allanleal** [comment]
Hi Joan, Reaktoro uses [conda for installation](https://reaktoro.org/installation/installation-using-conda.html), so uninstalling it is now a simple task as `conda remove reaktoro`.
