### ISSUE TITLE
Update repository and make it official

### ISSUE THREAD

**Issue by alexandrebbruno** [reaktoro/Reaktoro#3]
Hey @allanleal,

Since I'm a member of the project. 
Can I help you with the process of migrate from bitbucket to here? 

I suggest that we divide this activity as follow:
- [x] update this repository
- [x] close bitbucket's issue and create a issue which informs that Reaktoro has been moved to github. (similar to https://bitbucket.org/pytest-dev/pytest/issues?status=new&status=open)
- [x] informe at the bitbucket readme file that Reaktoro development has been moved to github

What do you think?

**Comment by allanleal** [comment]
Yes @alexandrebbruno , please help me with this migration. Let's turn develop branch in bitbucket to master branch here. Once this is finished, I'll then close the Bitbucket account and place a notice there in the README file.

**Comment by tadeu** [comment]
@allanleal, I can add update `master` here with `develop` from Bitbucket. If you wish, I can also rename master here to `old-master-github`, and bring `master` from Bitbucket as `old-master`.

Since updating `master` here needs a `push --force` (can't be done via pull request), I would need that you add me as collaborator with push access.

**Comment by tadeu** [comment]
@allanleal, thanks, it's done already:

* `github/master` -> `github/old-master-github`
* `bitbucket/master` -> `github/old-master-bitbucket`
* `bitbucket/develop` -> `github/master`

Only thing missing now is to close Bitbucket issues and update things there to inform that it has moved to GitHub, I guess you're going to do this, since you have the permissions there?

**Comment by allanleal** [comment]
Done! Check [Reaktoro's BitBucket main page](https://bitbucket.org/reaktoro/reaktoro) and [Reaktoro's BitBucket Issues](https://bitbucket.org/reaktoro/reaktoro/issues?status=new&status=open).

**Comment by nicoddemus** [comment]
Hi @allanleal, I think it is worth creating a single issue that says the repository has been moved to GitHub, similarly to what has been done on pytest: https://bitbucket.org/pytest-dev/pytest/issues?status=new&status=open
