### ISSUE TITLE
`speciate` is creating species that are not present in the database

### ISSUE THREAD

**Issue by tadeu** [reaktoro/reaktoro#414]
When using `speciate` with the Thermoddem database, it's returning a system containing `FeCl2!` and `FeO!` (with this extra `!`), which is not present in the database, see:

```python
import reaktoro as rkt

db = rkt.PhreeqcDatabase("thermoddem-v1.10.dat")
species = ["H2O", "Cl-", "Illite(FeII)"]
formulas = [str(db.species(s).formula()) for s in species]
print(formulas)
  
water = rkt.AqueousPhase(rkt.speciate(formulas))
water.set(rkt.ActivityModelPhreeqc(db))

mineral = rkt.MineralPhases(rkt.speciate(formulas))

system = rkt.ChemicalSystem(db, water, mineral)

for s in system.species():
    try:
        db.species(s.name())
    except RuntimeError as e:
        print(e)
        print(s.repr())
```

Output:

```
['H2O', 'Cl-', 'K0.85Fe0.25Al2.35Si3.4O10(OH)2']

***ERROR*** Could not find any Species object with name FeCl2!.

FeCl2!
***ERROR*** Could not find any Species object with name FeO!.

FeO!
```

This is also reproduced in this [notebook](https://gist.github.com/tadeu/d62f1a2e25bc3ca89f05ba307321b4ae).

**Comment by allanleal** [comment]
Hi @tadeu - in a `ChemicalSystem`, all species must have an unique name identifier. FeO is used in the thermoddem database for both the aqueous species and mineral. At construction of the `ChemicalSystem` object, `!` is appended to the name duplicates, to make them unique (e.g., FeO, FeO!). 

This name is used only in the chemical system, not in the database. This explains why you cannot find that species in the database.

Note that `db.species("FeO")` is going to return the aqueous species variant, because it is the first in the list of all species with name `FeO`. To get the mineral, you would need to find only among the solid species. 

What is important here is that the species in the chemical system you create are correctly selected: FeO aqueous in the aqueous phase, and FeO solid as a pure mineral phase. 

Hope this clarifies. I'll close this as I think it is not an issue, but happy to reconsider otherwise.

**Comment by tadeu** [comment]
OK, thanks @allanleal!
