### ISSUE TITLE
Implement operator== to ChemicalSystem

### ISSUE THREAD

**Issue by armandoeng** [reaktoro/reaktoro#55]
As one of the most important classes (which holds sensitive information), I think it should have a operator== to not just compare vector sizes, but the content of it, to judge if they are equal.

auto ChemicalSystem::operator==(const ChemicalSystem& other)
{
   const auto& impl = this->pimpl;
  const auto& other_impl = other.pimpl;
   return impl == other_impl  || (impl->phases == other_impl ->phases && impl->species== other_impl ->species);
}

Probably it would have to implement an operator== to Phase and Species class as well.

**Comment by allanleal** [comment]
This is not going to be simple, because these classes have `std::function` objects. I'm not sure yet how these are compared (say, a comparison of a copy of `std::function` object with its original results in `true`)?

In general, one should only have a single instance of `ChemicalSystem` class, with all species/phases that comprises all cases in the modeling.

**Comment by armandoeng** [comment]
Not necessary, as the philosophy is to use just one ChemicalSystem.

**Comment by allanleal** [comment]
Great - yes, we should promote the use of a single `ChemicalSystem` object and the use of `Partition` for customizing what should not be considered when doing the calculations (e.g., setting a gaseous phase to be inert for the sake of chemical equilibrium calculations using `Partition::setInertPhases` method).
