### ISSUE TITLE
Allow a special function to copy between different ChemicalStates

### ISSUE THREAD

**Issue by armandoeng** [reaktoro/reaktoro#56]
If I have two different ChemicalStates, with different ChemicalSystems (which have different phases and species). But they have some species in common, and I want to copy them. 
It could have a special function to allow that copy, which verify all the species that both have, and copy the amounts.

**Comment by allanleal** [comment]
A method ```transferAmountsOfCommonSpecies(fromstate, tostate);```?

But a class might be more suitable, because then we can save the map of common indices. 

```
ChemicalStateIntersection intersection(sytem1, system2);
```

Not sure yet. Also, we need to discuss if this usage (with more than one `ChemicalSystem`) should be advocated and promoted.

Can you post a convincing use case for this, that cannot be resolved by using a single `ChemicalSystem` object that comprises all your requirements?

**Comment by armandoeng** [comment]
As talked, this will not be necessary anymore.
