### ISSUE TITLE
Formatting of ChemicalState output

### ISSUE THREAD

**Issue by martinvoigt** [reaktoro/reaktoro#57]
The standard printed output of a ChemicalState object is quite useful to quickly check the state of a system, but it would be great if this output would be automatically formatted if printed in a Jupyter Notebook environment.

For example, the output is too wide for the standard Jupyter cells so that the columns are line wrapped, which is hard to read:
![image](https://user-images.githubusercontent.com/36659258/53728754-58939300-3e6b-11e9-940b-3ea0e8b09cd3.png)

A nice way would be to have it shown similar to a Panda data frame object, which automatically add a horizontal scroll bar if too wide:
![image](https://user-images.githubusercontent.com/36659258/53728856-909ad600-3e6b-11e9-8cb5-fa0fd3a3b56d.png)

**Comment by allanleal** [comment]
I think this should be relatively easy to do by creating a converter from `ChemicalState` to a python dictionary:

~~~python
state = equilibrate(problem)

df = pd.DataFrame(data=dict(state))
~~~

and from here you print the table.

However, how do you think we should structure/organize this dictionary from a geochemist perspective? I ask because in the table above we have several sections: 

1. for temperature and pressure
2. for element related state
3. for species related state
4. for phase related state
5. for aqueous phase state (which I don't think should be output by default, because some systems might not have an aqueous phase)

How could the dictionary be formatted so that panda will plot all these sections nicely (I mean, panda will understand the structure of the dict)?

**Comment by martinvoigt** [comment]
> However, how do you think we should structure/organize this dictionary from a geochemist perspective? I ask because in the table above we have several sections:
> 
> 1. for temperature and pressure
> 2. for element related state
> 3. for species related state
> 4. for phase related state
> 5. for aqueous phase state (which I don't think should be output by default, because some systems might not have an aqueous phase)
> 
> How could the dictionary be formatted so that panda will plot all these sections nicely (I mean, panda will understand the structure of the dict)?

Would it be possible to have the standard output be a combination of a DataFrame output and normal text output? Let's same show some basic properties first (temperature, pH, ...) and then tables for phase compositions and saturation states? Maybe it would even be possible to have some sort of "expand" for the longer tables, so that they are hidden first?

See my answer in #58 for what I personally think should be shown by default...

**Comment by allanleal** [comment]
> Would it be possible to have the standard output be a combination of a DataFrame output and normal text output?

Do you have an example for this? What would be "normal text"? Do you mean a more tight integration of Reaktoro and `DataFrame` from `pandas`? 

I created issue #59 to discuss implementation details and requirements so that both your issues #58 and #59 be addressed together. Let me know there if proposed workflow to achieve what you want is suitable.

**Comment by allanleal** [comment]
Hi Martin. The output in Reaktoro has been improved in Reaktoro v2. See examples in these tutorials:

* [Computing chemical properties](https://reaktoro.org/tutorials/basics/computing-chemical-properties.html)
* [Computing aqueous properties](https://reaktoro.org/tutorials/basics/computing-aqueous-properties.html)

Here is an example of the printed table for an object of class [**AqueousProps**](https://reaktoro.org/api/classReaktoro_1_1AqueousProps.html):

![image](https://user-images.githubusercontent.com/5825588/152538805-0f90a314-41f9-4a9b-9120-9375600b6c50.png)

There are plans to further improve this output (e.g., interactive HTML tables), but for the moment I think this issue is resolved. Thanks for your feedback and suggestions.
