### ISSUE TITLE
Convergence problem on GaseousPhase

### ISSUE THREAD

**Issue by alexandrebbruno** [reaktoro/reaktoro#72]
Investigate the reason why Reaktoro's convergence is related with the order that we add the species on gaseous phase. 

a system which the gaseous phase is added as:
```
ChemicalEditor editor(db);
editor.addAqueousPhaseWithElements("H O C S");
editor.addGaseousPhase({ "H2O(g)" , "CO2(g)",   "H2S(g)"  });

ChemicalSystem system(editor);
```
do not converge

a system which the gaseous phase is added as:
```
ChemicalEditor editor(db);
editor.addAqueousPhaseWithElements("H O C S");
editor.addGaseousPhase({"CO2(g)",  "H2O(g)" ,  "H2S(g)"  });

ChemicalSystem system(editor);
```
converge

Check the "demo-investigate-gaseous-initialization.cpp" on https://github.com/ESSS/reaktoro/tree/fb-RES-127-investigate-gaseous-phase-initialization to see this behavior.

**Comment by allanleal** [comment]
Thanks @alexandrebbruno - I'll have a look at this on Thursday. Order of species causing convergence issues is in most cases related to round-off errors not being properly addressed (or avoided).

**Comment by alexandrebbruno** [comment]
Great, thanks a lot :)
You will probably give a look on this early but, as soon as I finish the study of adding an the oleic phase I can also give a hand on this.

**Comment by allanleal** [comment]
So, I had the chance to look into this. The dirty and quick fix is adding a tiny amount of O2 to react with the other substances:

~~~c++
problem.add("O2", 1, "umol"); // where umol is 1e-6 mol (you can try 1e-12)
~~~

This issue is indeed caused by round-off errors. So, adding 1e-6 moles of O2 corrects the bad numerical behavior. 

The new minimization algorithm implemented in Optima (reaktoro/optima) should be able to solve this problem without this minor addition of O2. 

I still, however, have not had the time to couple new Optima library in Reaktoro. :disappointed:

**Comment by alexandrebbruno** [comment]
Ok, I will do it for now and mark this issue as closed!
thanks, I was stuck on this problem for a while :P

**Comment by allanleal** [comment]
Let me give you more details on this problem, and why adding a tiny amount of O2 solves it.

The element O in H2O and O2 are the **same**, but they are slightly different mathematically. This mathematical difference is subtle, and it comes from the fact that the *oxidation state* (OS) of O in H2O and O2 are -2 and 0. 

Your recipe adds no substances with O(0), only O(-2). This creates a corner case during the computation of equilibrium, in which the sum of species with O(0) needs to be (sharp) zero. However, the equations are rearranged in the algorithm, and this rearrangement might actually cause this sum to be equal a negative small value (round-off error converting what was zero to some -Ɛ, e.g., -1e-15).

Since the amounts of species are positive, there is no way to find amounts of species with O(0) that 
satisfy this constraint.

Thus, adding, say, 1e-12 moles of O2, mitigates this problem.

In the new version of Optima, this problem is addressed.
